apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-panels
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: k8s-http-routes
      repoURL: https://accurate0.github.io/inf-k8s
      targetRevision: 1.2.0
      helm:
        valuesObject:
          routes:
            - name: solar-panels-route
              crowdsecBouncer: true
              gateway:
                name: shared-gateway
                namespace: envoy-gateway-system
              hostnames:
                - solar-panels.anurag.sh
              rules:
                - backendRefs:
                    - name: solar-panel-web
                      port: 3000
                  matches:
                    - path:
                        type: PathPrefix
                        value: /
                - backendRefs:
                    - name: solar-panel-api
                      port: 8000
                  matches:
                    - path:
                        type: PathPrefix
                        value: /api
    - repoURL: https://github.com/Accurate0/solar-panels.git
      name: application
      path: kubernetes
      kustomize:
        images:
          - solar=ghcr.io/accurate0/solar:${ARGOCD_APP_REVISION}
          - solar-web=ghcr.io/accurate0/solar-web:${ARGOCD_APP_REVISION}
  destination:
    server: https://kubernetes.default.svc
    namespace: solar-panels
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
