services:
  solar:
    build:
      dockerfile: Dockerfile
      args:
        - BINARY_NAME=solar
    ports:
      - "8000:8000"
    links:
      - "db:database"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:test@database/bot
      - DISCORD_TOKEN
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 1s

  db:
    image: timescale/timescaledb:latest-pg16
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries='timescaledb'
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 90s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
