apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: solar-secret
  namespace: bom
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: solar-panels-cb-0h
        envSlug: prod
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReference:
    secretName: solar-managed-secrets
    secretNamespace: solar-panels
    creationPolicy: "Owner"
