apiVersion: v1
kind: Service
metadata:
  name: solar-panel-api
  namespace: solar-panels
spec:
  selector:
    app: solar
  ports:
    - name: app
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: solar-panel-web
  namespace: solar-panels
spec:
  selector:
    app: solar-web
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
