name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-web:
    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@main
    with:
      directory: web
      image-name: solar-web
      docker-build-args: ""
      use-rust-caching: true

  build:
    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@main
    with:
      directory: .
      image-name: solar
      docker-build-args: |
        BINARY_NAME=solar
      use-rust-caching: true

  deploy:
    needs:
      - build
      - build-web
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s.yaml@main
    with:
      application-name: solar-panels
      source-name: application
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
